# Generated by Django 4.2.5 on 2023-10-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='id',
        ),
        migrations.AddField(
            model_name='hospital',
            name='cnes',
            field=models.CharField(default='0000000', max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='telefone',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='categoria',
            field=models.CharField(choices=[('HOSPITAL_PUBLICO', 'Público'), ('HOSPITAL_PRIVADO', 'Privado'), ('HOSPITAL_FILANTROPICO', 'Filantrópico')], default='', max_length=100),
        ),
    ]
