# Generated by Django 4.2.5 on 2023-10-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0002_remove_hospital_id_hospital_cnes_hospital_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='endereco',
            new_name='endereço',
        ),
    ]
