# Generated by Django 4.2.5 on 2023-11-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0003_rename_endereco_hospital_endereço'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
