# Generated by Django 4.2.5 on 2023-10-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0003_alter_hospital_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hospital',
            table=None,
        ),
    ]
