# Generated by Django 4.2.5 on 2023-10-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0004_alter_hospital_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='cep',
            field=models.CharField(max_length=20),
        ),
    ]
