# Generated by Django 4.2.5 on 2023-10-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0004_alter_hospital_cep_alter_hospital_cnes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='municipio',
            field=models.CharField(default='', editable=False, max_length=150),
        ),
    ]
