# Generated by Django 4.2.5 on 2023-11-26 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0004_rename_endereço_hospital_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='atendimento',
        ),
    ]
