# Generated by Django 4.2.5 on 2023-11-26 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0005_remove_avaliacao_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='horario_atendimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='horario_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='horario_saida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
