# Generated by Django 4.2.5 on 2023-10-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0005_alter_hospital_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='categoria',
            field=models.CharField(choices=[('Público', 'Público'), ('Público', 'Privado')], default='', max_length=100),
        ),
    ]
