# Generated by Django 4.2.5 on 2023-10-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0006_alter_hospital_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='categoria',
            field=models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado')], default='', max_length=100),
        ),
    ]
