# Generated by Django 4.2.5 on 2023-11-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0006_avaliacao_horario_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
