# Generated by Django 4.2.5 on 2023-11-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0009_dados_altura_dados_tipo_sanguineo_alter_dados_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='exercicio',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dados',
            name='exercicio_frequencia',
            field=models.CharField(choices=[('n', 'Não'), ('d', 'Diariamente'), ('s', 'Semanalmente'), ('m', 'Mensalmente'), ('a', 'Anualmente')], default='n', max_length=200),
        ),
        migrations.AddField(
            model_name='dados',
            name='fumo_alcool',
            field=models.CharField(choices=[('n', 'Não'), ('d', 'Diariamente'), ('s', 'Semanalmente'), ('m', 'Mensalmente'), ('a', 'Anualmente')], default='n', max_length=200),
        ),
    ]
