# Generated by Django 4.2.5 on 2023-11-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0010_dados_exercicio_dados_exercicio_frequencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='exercicio',
            field=models.CharField(default='Nâo informado', max_length=200),
        ),
    ]
