# Generated by Django 4.2.5 on 2023-12-01 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0016_cirurgia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirurgia',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
