# Generated by Django 4.2.5 on 2023-12-01 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicial', '0018_internacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicao_familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao', models.CharField(default='N/A', max_length=200)),
                ('grau_parentesco', models.CharField(choices=[('1', '1° Grau'), ('2', '2° Grau'), ('3', '3° Grau')], default='1', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicao_familiar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
