# Generated by Django 4.2.5 on 2023-12-02 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicial', '0019_condicao_familiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Medicamento com prescrição'), ('2', 'Medicamento sem prescrição')], default='1', max_length=200)),
                ('medicamento', models.CharField(default='N/A', max_length=200)),
                ('frequencia', models.CharField(choices=[('n', 'Não'), ('d', 'Diariamente'), ('s', 'Semanalmente'), ('m', 'Mensalmente'), ('a', 'Anualmente')], default='n', max_length=200)),
                ('numero_frequencia', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
