# Generated by Django 4.2.5 on 2023-12-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0020_medicamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sintomas',
            name='data',
        ),
    ]
