# Generated by Django 4.2.5 on 2023-12-02 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0022_alter_avaliacao_data_alter_dados_tipo_sanguineo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
